### ISSUE TITLE
El syncronizer manual debe poder correrse para todos los nodos de forma idéntica a como corre automáticamente, además de poder seleccionar un nodo particular

### ISSUE THREAD

**Issue by abenassi** [datosgobar/django-datajsonar#132]

**Comment by lucaslavandeira** [comment]
@abenassi esto si no me equivoco lo podés hacer cuando no seleccionas ningún nodo (opción default). Lo que sí es cierto es que es poco amigable que el mensaje sea  `-------`, podríamos poner algo más descriptivo, como "Todos los nodos", te parece?

**Comment by lucaslavandeira** [comment]
![image](https://user-images.githubusercontent.com/19612265/57398083-929f4f00-71a4-11e9-8316-219ee28acc9b.png)

**Comment by abenassi** [comment]
@lucaslavandeira sí me parece bien poner "Todos los nodos" como opción. De
todas maneras yo había probado "-----------" y tampoco funcionaba. Si
hubiera funcionado de esa forma estaba ok también.
