### ISSUE TITLE
Metadatos enriquecidos en el admin de django

### ISSUE THREAD

**Issue by poligarcia** [datosgobar/django-datajsonar#53]
Es deseable poder visualizar y eventualmente modificar los metadatos enriquecidos desde el administrador de django.

Como la entidad que modela estos metadatos tiene una relación polimórfica con los distintos miembros del modelo de metadatos, creo que sería conveniente que el modelo de metadatos eriquecidos no tenga una pantalla propia en el admin de django, sino que se puedan visualizar y editar desde un _inline_ del admin de django en la pantalla del modelo con el cual se relacionan.

Es decir, si ingreso a visualizar el catálogo *sspm*, en algún apartado del admin podré visualizar los metadatos enriquecidos que le corresponden.

**Comment by lucaslavandeira** [comment]
Resuelto en #55
