### ISSUE TITLE
Integrar lectura forzada cuando se especifica un "format"

### ISSUE THREAD

**Issue by abenassi** [datosgobar/django-datajsonar#91]
Este issue es un follow up del #225 de pydatajson y el #90 de django-datajsonar

**Comment by abenassi** [comment]
No estaría funcionando por ahora la lectura de CKAN con monitoreo-apertura.

**Comment by lrromero** [comment]
@abenassi Ahí estuve investigando el problema de base y resulta que `monitoreo-dev` no puede resolver la url de http://datos.jus.gob.ar . Esto sería un tema para que encare @cesarquilmes cuando vuelva para que defina bien las reglas de ruteo. Voy cerrando este issue, abrís otro para trackearlo y que no se nos olvide cuando vuelva Cesar?
